# -*- coding: utf-8 -*-
"""5.4exploracao_dados.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1MQpEPgmZc0JzmYeqtgzvpwThtjhtaNg7

# ##Exploração de Dados
"""

#Vamos começar a segunda etapa do pipeline dos dados, na qual vocês farão a exploração dos dados coletados.
#Existem várias formas de se explorar dados e o Python Pandas fornecem muitos recursos para essa ação.
#Lista de itens obrigatórios para essa exploração

import pandas as pd
!pip install -U pandasql
import pandasql

df = pd.read_csv('script_coleta.csv')
#Saber a quantidade de linhas, observações ou variáveis que foram coletadas.
df.shape
df.columns
df.count()
df.info
df.var

#Quantos relatos ocorreram por estado em ordem decrescente?
q = """SELECT *, count(*) as total FROM df GROUP BY State ORDER BY total DESC;"""
sql = pandasql.sqldf(q)

#Remover possíveis campos vazios (sem estado).
#query = """ SELECT State FROM df where situacao = ' ' ; """

query = """ SELECT * FROM df WHERE State != '';"""
sql = pandasql.sqldf(query)

#Limitar a análise aos estados dos Estados Unidos.
df_estados=pd.DataFrame()
df_estados['sigla'] = ['AL','AK','AR','AZ','CA','KS','NC','SC','CO','CT','ND','SD','DE','FL','GA','HI','ID','RI','IL','IN','IA','KY','LA','ME',
               'MD','MA','MI','MN','MS','MO','MT','NE','NV','NH','NJ','NY','NM','OK','OH','OR', 'PA','TN','TX','UT','VT','VA','WV','WA','WI','WY']
estados = """ SELECT * FROM df, df_estados WHERE State = sigla; """
sql_eua = pandasql.sqldf(estados)

#Consulta por cidades, com o objetivo de saber quais contêm o maior número de relatos (cidades que apresentem ao menos 10 relatos).
cidades = """ SELECT *,count(Posted) as relatos  FROM sql_eua GROUP BY City ;"""
sql_cidades = pandasql.sqldf(cidades)

est = """ SELECT * FROM sql_cidades WHERE relatos >= 10 ORDER BY relatos DESC; """
sql_e = pandasql.sqldf(est)

#Com o dado anterior, responder a seguinte pergunta: por que será que essa é a cidade que possui mais relatos?
#Porque a cidade de Phoenix possui maior quantidade de relatos registrados no portal, o motivo e porque possui 
#registros na história de que foram visualizados luzes encontradas na cidade durante o período de vinte anos, 
#com isso selecionaram para serem feitas a coleta dos dados. E esses acontecimentos ocorrem durante os anos de 1997, 
#e esse fato repetiu-se durante os anos de 2007, 2008 e 2009 em seguidas repetições. Isso pode ser uma das motivações encontrados para que 
#a cidade de Phoenix no estado do Arizona ter uma maior quantidade de relatos.

#Fazer uma query exclusiva para o estado com maior número de relatos, buscando cidades que possuam um número
#superior a 10 relatórios. Enfatizar a cidade, a quantidade de relatos e formato do objeto não identificado.
estados_usa = """ SELECT *,count(Posted) as relatos  FROM sql_eua GROUP BY State ;"""
estados_us = pandasql.sqldf(estados_usa)

relatos_estados = """ SELECT State,City,Shape, MAX(relatos) FROM estados_us ORDER BY relatos DESC; """
sql_y = pandasql.sqldf(relatos_estados)

sq = """ SELECT sql_cidades.State,sql_cidades.City,sql_cidades.Shape,sql_cidades.relatos FROM sql_y,sql_cidades WHERE sql_cidades.relatos > 
10 AND sql_cidades.State = sql_y.State ORDER BY sql_cidades.relatos DESC;""" 
sql = pandasql.sqldf(sq)

#retira os campos vázios de Shape
#sq_shape = """ SELECT sql_cidades.State,sql_cidades.City,sql_cidades.Shape,sql_cidades.relatos FROM sql_y,sql_cidades WHERE sql_cidades.Shape != '' AND 
#sql_cidades.Shape != 'Unknown' AND sql_cidades.relatos > 10 AND sql_cidades.State = sql_y.State ORDER BY sql_cidades.relatos DESC;""" 
#sql = pandasql.sqldf(sq_shape)