# -*- coding: utf-8 -*-
"""5.8_acrescimo_variaveis.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1LhyBaGB3DU9D0l74cJL8vZkPRJTxqrGn
"""

import pandas as pd
from datetime import datetime
import datetime

#1.Carregar o seu arquivo df_OVNI_limpo.csv em um dataframe;

df = pd.read_csv("df_OVNI_limpo.csv")

#2.Dividir o conteúdo da coluna Date / Time em duas novas colunas no mesmo dataframe e deletar
# a coluna Date / Time.
#transforma a coluna Date/Time em datetime
df['Date / Time'] =pd.to_datetime(df['Date / Time'])

#criar a coluna sight_date
df ['Sight_Date']= df['Date / Time'].dt.strftime('%m/%d/%Y')
#criar a coluna sight_time
df ['Sight_Time'] = df ['Date / Time'].dt.strftime('%H:%M:%S')

#excluindo as colunas date/time e unnamed: 0
df.drop(columns=['Date / Time','Unnamed: 0',],axis=1 ,inplace=True)

#3. Fazer o mesmo procedimento para dias da semana. 
#Será que existe um dia da semana com mais ocorrências de relatórios para OVNIs?
# Para descobrir isso, você deve criar uma nova coluna chamada weekdays.
df ['Sight_Weekdays']=  pd.to_datetime(df['Sight_Date']).dt.day_name()

#Será que existe um dia da semana com mais ocorrências de relatórios para OVNIs?
# Sim existe esse dia e o dia é a terça feira.

#4. Separar as variáveis mês (Month) e dia (Day). Desse modo, será possível refinar as pesquisas.
df ['Sight_Month'] = pd.to_datetime(df['Sight_Date']).dt.strftime('%m') 
df ['Sight_Day'] = pd.to_datetime(df['Sight_Date']).dt.strftime('%d')

#5. Salvar o dataframe resultante em um arquivo .csv com o nome: 'df_OVNI_preparado'.
df.to_csv("df_OVNI_preparado.csv", index=False)